# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Build Kernel
        uses: froyoandroid/kernel_build_action@main
        with:
          kernel-url: https://gitlab.com/firenza20/kernel-chopin
          kernel-branch: refactor
          config: chopin_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          other-clang-url: https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/17062026/neutron-clang-17062026.tar.zst
          disable-lto: true
          extra-make-args: '["-s"]'
          anykernel3: true
          anykernel3-url: https://github.com/froyoandroid/AnyKernel3
